### ISSUE TITLE
IOError: Couldn't find file '01_hp/13_hermione_main/body_208b.png'

### ISSUE THREAD

**Issue by ghost** [stg-trainer-annon/BT-Silver-Base#10]
When the Breast molester & Butt molester an error:
IOError: Couldn't find file '01_hp/13_hermione_main/body_208b.png'.
[log.txt](https://github.com/stg-trainer-annon/BT-Silver-Base/files/93990/log.txt)

**Comment by ta12345** [comment]
getting a similar error, but body_213.png

there may be missing files, because they only go up to 207 in that folder

**Comment by stg-annon** [comment]
those files are on git try re-downloading and merge the files in

**Comment by ghost** [comment]
Thank you. These errors are gone.
