### ISSUE TITLE
Wrong dialogue when equipping clothing items

### ISSUE THREAD

**Issue by skojer** [stg-trainer-annon/BT-Silver-Base#120]
SRC: WT:S 1.24

Applies to pretty much all clothing items. For example a Griffindor skirt is being talked about as if it was jeans. Accessories don't seem to suffer from this though. Normal Jeans are treated as the standard skirt, while shorter ones are treated as a shorter skirt.

**Comment by zddguu** [comment]
The current dress-up system is still very much a work in progress by @Mad-Merlin
