### ISSUE TITLE
post ending and New game+ crash

### ISSUE THREAD

**Issue by thepolish1** [stg-trainer-annon/BT-Silver-Base#125]
Ending the game i get the Thank you message, then a crash report. If i try open up a game+ i get another crash report

![thank you](https://user-images.githubusercontent.com/36069524/35730002-616135e0-0808-11e8-84ca-db6fbedf73b9.jpg)
[traceback - end game.txt](https://github.com/stg-trainer-annon/BT-Silver-Base/files/1689065/traceback.-.end.game.txt)
[traceback - New Game+.txt](https://github.com/stg-trainer-annon/BT-Silver-Base/files/1689066/traceback.-.New.Game.txt)

**Comment by slavetrainermod** [comment]
Fixed in latest commit.
