### ISSUE TITLE
Error getting "DAHR's ticket"

### ISSUE THREAD

**Issue by ghost** [stg-trainer-annon/BT-Silver-Base#13]
After reading "My Dear Waifu" five times out of five error appears:
_IOError: Couldn't find file '03_hp/18_store/06.png'_
It is necessary to fix the file "BT-Silver-Base/game/00_hp_rpy/17_waifu.rpy" on line 457.
[log.txt](https://github.com/stg-trainer-annon/BT-Silver-Base/files/110897/log.txt)

**Comment by stg-annon** [comment]
fixed (assorted fixes 1/30/16) thanks
