### ISSUE TITLE
Overlay images in custom favour "Show her who's in charge"

### ISSUE THREAD

**Issue by ghost** [stg-trainer-annon/BT-Silver-Base#14]
During the quest, Hermione looks a little bad.
Just after the end of the event, at the screen remains Hermione Chibi.

The same problem with the imposition appears when moving Fawkes in Hermione.

![1](https://cloud.githubusercontent.com/assets/16745293/12697301/2be0d024-c791-11e5-824d-272d1deaee83.png)
![2](https://cloud.githubusercontent.com/assets/16745293/12697305/2be3d206-c791-11e5-9e7e-a95b3a486006.png)
![3](https://cloud.githubusercontent.com/assets/16745293/12697303/2be33382-c791-11e5-964f-ea86bba45578.png)
![4](https://cloud.githubusercontent.com/assets/16745293/12697302/2be21e98-c791-11e5-8d4a-b7c01e19065b.png)
![5](https://cloud.githubusercontent.com/assets/16745293/12697304/2be3c252-c791-11e5-9afc-8d94bcfa75bf.png)

![21](https://cloud.githubusercontent.com/assets/16745293/12697551/eefc3a02-c797-11e5-92d3-0305ab692f24.png)

**Comment by stg-annon** [comment]
these issues should be resolved in the last push ("fixed" custom events)
