### ISSUE TITLE
Bug? Healing potions don't appear in the cabinet anymore, making the starting Snape duel almost impossible.

### ISSUE THREAD

**Issue by CheeseburgerWithFries** [stg-trainer-annon/BT-Silver-Base#152]
Version 141f586

I've tested this about 4 times each in normal and easy difficulty, but the cabinet is no longer giving out healing potions. It's possible I just had horrendous RNG, but this seems more like a bug.

Without healing potions, the Snape duel at the beginning of the game is almost impossible. Even if you play things perfectly, the 'devil hand' attack will break through your defense and whittle down your health until you get a game over.

It's not a huge deal because you can skip past the Snape duel when starting a new game, but this still should be looked at.

**Comment by Mad-Merlin** [comment]
Thanks for the bug report!
I accidentally deleted a section of the code.
Should be fixed now.

**Comment by CheeseburgerWithFries** [comment]
Thanks! It's possible that code section also caused another bug that I just filed a report on.

See Issue #154 for details on that.

**Comment by CheeseburgerWithFries** [comment]
Seems fixed in cccd005
