### ISSUE TITLE
Bug. Cupboard now gives out infinite rewards per day.

### ISSUE THREAD

**Issue by CheeseburgerWithFries** [stg-trainer-annon/BT-Silver-Base#154]
Version 141f586

This occurs in both easy and normal difficulty.

Previously when you used the "Rummage through the cupboard" option, the game would give you a reward or not, and then that'd be it for the day.

In the current build, the cupboard gives infinite rewards if the player keeps selecting the option. If that day's reward is 19 gold, after ten clicks the player will have gotten 190 gold, and they can keep going. This applies to everything the cupboard gives, from Dumbledore's wine to lollipops to gold to stuffed owls.

**Comment by Mad-Merlin** [comment]
That's also fixes that.

**Comment by CheeseburgerWithFries** [comment]
Seems fixed in cccd005
