### ISSUE TITLE
Image bug in duel

### ISSUE THREAD

**Issue by ghost** [stg-trainer-annon/BT-Silver-Base#18]
If used heal bottle we get this for duration of duel
![102](https://cloud.githubusercontent.com/assets/16745293/12745524/b5de26bc-c9aa-11e5-8b0e-e0a32a4b877b.png)
![104](https://cloud.githubusercontent.com/assets/16745293/12745525/b5f6b092-c9aa-11e5-8bad-1d4caaf7ca83.png)
![106](https://cloud.githubusercontent.com/assets/16745293/12745526/b609c754-c9aa-11e5-9ab1-797a6ca804c7.png)

**Comment by stg-annon** [comment]
fixed (heal animation fix) thanks!
