### ISSUE TITLE
Include Advanced Saves in the game

### ISSUE THREAD

**Issue by elmagio** [stg-trainer-annon/BT-Silver-Base#19]
Since the large majority people who play this mod have already gone through the original game one or more time, it would be nice if it was possible to skip very far ahead in the story easily, to enjoy the best parts that have been modded in more easily, or just to skip to "Max Whoring" things immediately. The cheating that has been added in does a lot to make the game less tedious when replayed than it originally was, but I think this would make it even more seamless.

There could be 4 or 5 advanced saves on one of the save tabs, with varying levels of completion. 

PS: If you don't agree with including that kind of thing in the game for a reason or another, and it's just me being a lazy-bum, I would appreciate it if you shared some of your saves (if you have them) that are compatible with the 1.03 release, with me.

**Comment by stg-annon** [comment]
some new cheats have been added, this should help with your problem, any other suggestions are welcome

**Comment by elmagio** [comment]
Indeed, these new cheats basically solve any issue I add ! Thanks, and cheers !
