### ISSUE TITLE
Two new bugs

### ISSUE THREAD

**Issue by ghost** [stg-trainer-annon/BT-Silver-Base#20]
Thank you for your previous fixes!
I wanted to test if everything is Ok, but got out the new bugs.

At the beginning of the new games appear error ([log1.txt](https://github.com/stg-trainer-annon/BT-Silver-Base/files/129721/log1.txt)):
    File "game/00_hp_rpy/01_hp.rpy", line 296, in <module>
    IndexError: list assignment index out of range

I suppose should be set cs_existing_stock one line:
    $ cs_existing_stock = [False,False,False,False,False]

Also during the evening of the first after a duel appear error ([log2.txt](https://github.com/stg-trainer-annon/BT-Silver-Base/files/129720/log2.txt)):
    File "game/00_hp_rpy/33_mo.rpy", line 3016, in <module>
    NameError: name 's_head_xpos' is not defined

I think it's better set individual constants the default position of the head, or use a direct indication:
    label sna_head(text="",face="",xpos=330 ,ypos=380):
        if xpos != 330:
            $ s_head_xpos = xpos
        if ypos != 380:
            $ s_head_ypos = ypos

**Comment by stg-annon** [comment]
these bugs have been addressed in the last push, the reason xpos=character_xpos is that way is because if you were to call it to set the xpos the expectation is that it stays the value you set it to, as opposed to getting reset to the default value every time you call it. thanks for all the help!
