### ISSUE TITLE
Extra Chibi

### ISSUE THREAD

**Issue by ktn555** [stg-trainer-annon/BT-Silver-Base#32]
![3434](https://cloud.githubusercontent.com/assets/11589479/13093393/a463155c-d4ca-11e5-8195-615353202659.PNG)
The first few favors cause an additional chibi to spawn.

**Comment by stg-annon** [comment]
do you know what favor specifically?

**Comment by ktn555** [comment]
dance for me

**Comment by stg-annon** [comment]
fixed in the last push, thanks
