### ISSUE TITLE
store page not at the edge 

### ISSUE THREAD

**Issue by ktn555** [stg-trainer-annon/BT-Silver-Base#47]
![potionshopnotatedge](https://cloud.githubusercontent.com/assets/11589479/15917258/a7170e80-2dc0-11e6-99a2-749ef8f7b09e.PNG)

**Comment by ktn555** [comment]
Also the exit store button does not work.

**Comment by stg-annon** [comment]
addressed in commit 9944c920622382b6a2c56ad53738ee72936629df thanks
