### ISSUE TITLE
2 part events not firing 2nd part

### ISSUE THREAD

**Issue by flint76** [stg-trainer-annon/BT-Silver-Base#49]
The 2 part events such as give me you panties the evening part doesn't run

**Comment by stg-annon** [comment]
this issue should now be fixed

**Comment by flint76** [comment]
just tried using silver shell 1.06 and latest zip evening part of panty thief or wear my c*\* doesnt trigger and on panty thief after the 1st part panties dont appear in jerk **\* just says locked

**Comment by stg-annon** [comment]
this should be fixed in the latest version

**Comment by flint76** [comment]
nope tried fresh install shell 1.06 and both zip download of repository and svn check out sperate attempts neither work with save load top option still locked in jerk **\* says you lack the required item and if you select floor nothing fires at night

**Comment by stg-annon** [comment]
alright newest patch should fix it, try again.

**Comment by flint76** [comment]
yup both public shaming fire correctly now
good work really enjoy the work you've done

**Comment by stg-annon** [comment]
good to hear its working for you, thanks
