### ISSUE TITLE
Dress up during anal doesn't work as expected

### ISSUE THREAD

**Issue by bondamani** [stg-trainer-annon/BT-Silver-Base#5]
She dresses up in Lara's outfit instead of the ball dress during anal. Line 8847 in 23_personal_requests.rpy:

``` python
                    $ custom_outfit = 12
```

This should be 10 instead of 12.

Also, she doesn't change back to her normal outfit after the scene is over. To fix it, insert the following in Line 9580:

``` python
    $ custom_outfit = temp_outfit
    $ stockings = temp_stockings
```

**Comment by slavetrainermod** [comment]
Fixed, thanks.
