### ISSUE TITLE
Show them to me not working

### ISSUE THREAD

**Issue by flint76** [stg-trainer-annon/BT-Silver-Base#50]
When you click show them to me it runs butt molester instead
Also on reload all the red heart lvls clear but return if you run each event

**Comment by stg-annon** [comment]
show them to me should be fixed, thanks.

as for the reloading issue I am aware and working on it, it appears to be an issue with how renpy initializes data in init blocks as opposed to elsewhere. I should have a fix out soon, but ill need to do some testing first.

thanks again

**Comment by stg-annon** [comment]
the hearts should now be persistent, thanks.
