### ISSUE TITLE
How to get collar?

### ISSUE THREAD

**Issue by staahr** [stg-trainer-annon/BT-Silver-Base#52]
Hello folks!
First off: Great work with this mod, best i have seen yet, glad to be with you from the beginning.
Howerver, i jsut cant seem to figure out how to get the fkn collar :D

**Comment by stg-annon** [comment]
Hello, thanks for the kind words and support. To answer your question it appears all you need to do is get Hermione's whoring level above 23 then go to the accessories tab under Hermione's "-Inventory-" menu and select the collar, this should start the collar scenes. however I only know this from looking at the code mo wrote an I cannot test it in game until much later today I hope this helps.

**Comment by staahr** [comment]
i´ll look into that now,, just tried sgooting her whoring to lvl 23, but with the cheat it only gets to 22, but i know from a old save u can get to lvl 24

Edit: yes works find, thanks
