### ISSUE TITLE
Unable to progress after giving Hermione the ball dress

### ISSUE THREAD

**Issue by CMBuurns** [stg-trainer-annon/BT-Silver-Base#66]
Happend to me on both the stable 1.10 version and the latest dev build.
After giving Herminone the dress there should be a scene in which Snape tells you how to get home, but that doesn't trigger for me.

I've waited about 50 ingame days and have everything done and maxed as far as I know.

**Comment by slavetrainermod** [comment]
Fixed as of the next update. There is now an option in the gift tab that will start the final events.

**Comment by CMBuurns** [comment]
Awesome, thanks.
