### ISSUE TITLE
door cutoff in experimental version

### ISSUE THREAD

**Issue by slirith** [stg-trainer-annon/BT-Silver-Base#78]
regardless if windowed or full screen, no door. restarting doesn't help

**Comment by Asatim** [comment]
I have the same same problem! Please help, this game is awesome!
![bug wt silver](https://user-images.githubusercontent.com/31697216/30114211-77f85952-9317-11e7-913d-72a1cf842bd6.png)

**Comment by slavetrainermod** [comment]
Does this only occur in the GitHub version or does it also affect the mega version?

**Comment by Asatim** [comment]
Well, if I use the Mega version without copying and replacing the game folder with the experimental one, yes it works perfectly!
![bug wt silver 2](https://user-images.githubusercontent.com/31697216/30161692-f290b334-93d1-11e7-9cc8-75abcbf945cc.png)
