### ISSUE TITLE
Missing Files/Linkage? 

### ISSUE THREAD

**Issue by Sakkyoku-Sha** [stg-trainer-annon/BT-Silver-Base#86]
Running Version 1.23

The game runs fine, unless I click on the status image in the top right for characters. Then the following error message is given 

While loading <'Image' u'01_hp/13_characters/luna/clothes/uniform/skirt_0.png'>:
  File "game/script.rpy", line 14, in script call
    call select_start
  File "game/00_hp_rpy/19_my_screens.rpy", line 161, in script
    call screen stat_screen_luna
  File "renpy/common/000statements.rpy", line 471, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
IOError: Couldn't find file '01_hp/13_characters/luna/clothes/uniform/skirt_0.png'.

Given that this seems to be a missing file issue, is the problem on my end? or not?

**Comment by Kodlaken** [comment]
I also had this problem, I just made a copy of the skirt images that were already there and called it skirt_0, then it gave another error about there being no top_0 I used the same solution.

**Comment by zddguu** [comment]
I fixed it in pull #136

**Comment by slavetrainermod** [comment]
Fixed in latest commit.
